#' Gather all results generated by an analysis into a single dataframe.
#'
#' @param Tasks (dataframe)
#' @param tabRepo (string) Path to output tables.
#' @param userTag (string) String to append to results filenames.
#'
#' @return A dataframe with same columns as "xxx_results.csv".
#' @export
#'
#' @examples
gatherResults <- function(
  Tasks,
  tabRepo,
  userTag
) {
  D = NULL
  for(task in 1:nrow(Tasks)) {
    # Build file tag
    msTable = Tasks[task,'MS_file']
    CVTable = Tasks[task,'DMS_file']
    tag  = makeTag(CVTable, msTable, userTag)
    file = file.path(tabRepo,paste0(tag,'_results.csv'))
    if (!file.exists(file)) {
      message('>>> Error: Missing file:', file, '\n')
      stop(call.=FALSE)
    }
    M = read.csv(file = file, check.names = FALSE)
    D = rbind(D,M)
  }
  return(D)
}
